# This is a basic workflow to help you get started with Actions

name: Zip Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create release folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
    
    - name: Switch to Release Folder
      run: |
        cd release
        ls -la
        
    - name: Zip release folder
      run: zip -r release.zip . -x ".git/*" ".github/*"
        
    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/ninjanomnom/moth-chat-modpack/releases/tag/v1.1/assets?name=release.zip
        asset_path: ./release.zip
        asset_name: release.zip
        asset_content_type: application/zip
