# This is a basic workflow to help you get started with Actions

name: Zip Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Download LFS Files
      run: git lfs install && git lfs pull

    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./release
    
    - name: Switch to Release Folder
      run: |
        cd release
        ls -la

    - name: Recreate Github Release
      id: create_release
      uses: GongT/actions-recreate-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Stable
        draft: false
        prerelease: false
        
    - name: Zip Release Folder
      run: zip -r release.zip . -x ".git/*" ".github/*"

    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.zip
        asset_name: release.zip
        asset_content_type: application/zip
